// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXeWtHcQb7vPkty57C7WmNG8JnG31rnCg',
    appId: '1:421444973570:web:6167b08c936d5a61a3631b',
    messagingSenderId: '421444973570',
    projectId: 'triangle-b5312',
    authDomain: 'triangle-b5312.firebaseapp.com',
    storageBucket: 'triangle-b5312.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ1-UU00S2Mf3CTYwt1W2_0sRVLflJjGc',
    appId: '1:421444973570:android:4276122130a00278a3631b',
    messagingSenderId: '421444973570',
    projectId: 'triangle-b5312',
    storageBucket: 'triangle-b5312.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6I57E66AYTbPoMSh-z531WEUIOWW8RvQ',
    appId: '1:421444973570:ios:0b3171709eea01d5a3631b',
    messagingSenderId: '421444973570',
    projectId: 'triangle-b5312',
    storageBucket: 'triangle-b5312.appspot.com',
    iosClientId: '421444973570-622sg9irk2k8dadh8jaj50r0ot0ti3nk.apps.googleusercontent.com',
    iosBundleId: 'com.traingle.app',
  );
}
